### ISSUE TITLE
Keep comments?

### ISSUE THREAD

**Issue by Martii** [breeswish/express-minify#15]
Over at our project we could really use the keep comments option in this package from [_uglify-js_](https://www.npmjs.org/package/uglify-js) but still minify everything else _(in select JavaScript code)_... any chance of that here?

TIA.

**Comment by tiansh** [comment]
I'm not sure why, but...
Try this one: https://openuserjs.org/scripts/ts/Test_Script_for_Keep_Comments
It removed the comment 8
