### ISSUE TITLE
Don't minify but do everything else?

### ISSUE THREAD

**Issue by Martii** [breeswish/express-minify#17]
We were wondering if you would consider adding the feature of disabling minification but still parse and compile available types *(e.g. add a separate option in to negate the "Notice that this would also disabling CoffeeScript/SCSS/LESS/Stylus parsing for this response." for `response._no_minify`)*

Currently our project has two development modes detected... dev and dbg *(develompent and debug)*. When we are in debug mode we would like to be able to disable minification for extreme debugging purposes but still enable parsing and compiling. Currently there is nothing like `response._no_minification = true;`, or similar, to prevent `result = cssmin(content)` calls from happening similar to `response._no_cache`. e.g. perhaps something like `result = identifier._no_minification ? content : cssmin(content)`?

We can use another package in a very small group *(in their unusual way)* for our debug environment but it would be awesome to see this feature here as your package appears to be handling this according to the specs and is very clean in comparison.

Thanks so much for the consideration and this is definitely one of my more favorite packages. :)

**Comment by breeswish** [comment]
Hello. Now it is possible to disable minifying while preserving precompileing via `response._no_minify`  in version 0.1.2. :-)

**Comment by Martii** [comment]
Works great here! :) Thank you.
