### ISSUE TITLE
Support for `@import` ?

### ISSUE THREAD

**Issue by Martii** [breeswish/express-minify#18]
Hello again. This is going to be a bit tricky to explain but I will give it a go in a reduced test case form...

someSnippet.js

``` javascript
var express = require('express');
var minify  = require('express-minify');

var app = express();

/*
 * Bunch of other express specific intialization and then...
 */
express.static.mime.define({
  'text/less': ['less']
});

/*
 * Use minify
 */
app.use(minify());
```

someSnippet.html

``` html
<link rel="stylesheet/less" type="text/css" href="/source1.less">
```

source1.less

``` css
@import 'source2.less';

body {
  background-color: @my-color;
}
```

source2.less

``` css
@my-color: #ABC123;
```

Produces the following output at our [http://localhost:8080/source1.less](http://localhost:8080/source1.less):

``` json
{"type":"File","filename":"input","index":0,"line":1,"callLine":null,"column":0,"extract":[null,"@import 'source2.less';",""],"message":"'source2.less' wasn't found. Tried - source2.less,source2.less"}
```

... instead of the expected ...

``` css
body{background-color:#abc123}
```
1. Did I do something incorrectly with _express-minify_ initialization?
2. Do you support the `@import` statement? Currently we are using the _less-middleware_ package to achieve support.
3. If you do support the `@import` statement we are going to need some exposure to the `paths` option in _less_ too probably similar to #15 e.g. we currently pick through a series of `.less` files at different paths in our project tree and import them into our own `.less` from a different path.

As long as we don't use the `@import` statement and keep all variables and mixins in the same file _express-minify_ works with less parsing and compiling... however splitting them out doesn't seem to.

Any help would be greatly appreciated.

**Comment by breeswish** [comment]
Actually this is a hard problem, cause we don't know what is the FileSystem location only based on req. Any ideas?

**Comment by breeswish** [comment]
New ideas: allowing users to specify a LESS instance so that he/she can get control with the working directory configurations.

**Comment by breeswish** [comment]
You can specify LESS options now.
