### ISSUE TITLE
gzipping should be done after minification

### ISSUE THREAD

**Issue by nnIIInnjA** [breeswish/express-minify#48]
in your readme, you've put
`app.use(compression());
app.use(minify())`

shouldn't this be other way around ?

**Comment by breeswish** [comment]
Yes gzip should be done after minification. However `express-minify` and `compression` rewrite function to "hook" the output of the response thus the order is reversed.

Let's say, a hook is as simple as:

```js
var _send = res.send();
res.send = function (data) {
  // our own logic here
}
```

Then let's imagine multiple hooks (middleware A appears before middleware B):

```js
var _sendA = res.send();
res.send = function (data) {
  // A
  manipulateA();
}

var _sendB = res.send();
res.send = function (data) {
  // B
  manipulateB();
}
```

Now when calling `res.send`, the order would be:

```js
manipulateB
manipulateA
```

**Comment by nnIIInnjA** [comment]
I got it. thanks :)
